/**
 * index.js action types
 */

export const ADD_CATEGORIES = 'ADD_CATEGORIES';

export const ADD_POSTS = 'ADD_POSTS';
export const ADD_COMMENT_TOTAL = 'ADD_COMMENT_TOTAL';
export const EDIT_POST = 'EDIT_POST';
export const RESET_POSTS = 'RESET_POSTS';
export const UPDATE_POST_SCORE = 'UPDATE_POST_SCORE';
export const DELETE_POST = 'DELETE_POST';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const UPDATE_COMMENT_SCORE = 'UPDATE_COMMENT_SCORE';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_FROM_PARENT = 'DELETE_COMMENT_FROM_PARENT';